# Site-wide settings

title: "Modern Book Production"
description: "A visual description of the modern book-production process."
image: "modern-book-production.jpg"
url: "https://electricbookworks.github.io/modern-book-production"
